/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root dDACectory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STD_TYPES.h"
#include "MCAL_RCC_Private.h"
#include "MCAL_RCC_Interface.h"
#include "MCAL_RCC_Config.h"

#include "MCAL_GPIO_Interface.h"
#include "MCAL_GPIO_Config.h"

#include "MCAL_EXTI_Interface.h"

#include "MCAL_STK_Interface.h"

#include "GoodSound.h"
#include "BravoSound.h"
/**********************************************************************************************************************
 *  FUNCTION PROTOTYPE
 *********************************************************************************************************************/

void DAC_vReceiveCallBack(void);
void DAC_vPlayAudioCallBack(void);
/**********************************************************************************************************************
 *  MAIN FUNCTION
 *********************************************************************************************************************/

int main(void)
{
	/* Step 1 : System Clock is 16 MHz from HSI */
  MCL_RCC_vInitSysClk(&RCC_GPIO_Config);

	MCL_STK_vInit(&STK_G_Config);
	/* Step 2 : Init GPIO Port A */
for(u8 Local_u8Index = 0; Local_u8Index < GPIO_PIN8; Local_u8Index++)
{
	MCL_GPIO_vSetPinCfg(GPIOA, Local_u8Index, &GPIO_OUT_Config);
}

	MCL_STK_vSetIntervalPeriodic(125 , DAC_vPlayAudioCallBack);
/* Loop forever */
	while(1){

	}
}


void DAC_vPlayAudioCallBack(void)
{
	static u16 Static_u16SampleIndex = 0;
	if(Static_u16SampleIndex++ < Bravo_raw_len)
		{MCL_GPIO_vWritePort(GPIOA, Bravo_raw[Static_u16SampleIndex]);}
	else
		Static_u16SampleIndex = 0;
}
