/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STD_TYPES.h"
#include "MCAL_RCC_Interface.h"
#include "MCAL_RCC_Private.h"
#include "MCAL_RCC_Config.h"

#include "MCAL_GPIO_Interface.h"
#include "MCAL_GPIO_Config.h"

#include "MCAL_SPI_Interface.h"
#include "MCAL_SPI_Config.h"

#include "HAL_TFT_Interface.h"
#include "HAL_TFT_Config.h"

#include "MCAL_STK_Interface.h"
#include "Shafeeq.h"
/***********************
 * CONSTANT MACROS
 **********************/

/**********************************************************************************************************************
 *  Global Variables
 *********************************************************************************************************************/
u8 SPI_u8Data = 0;
/**********************************************************************************************************************
 *  FUNCTION PROTOTYPE
 *********************************************************************************************************************/

void SPI_vReceiveCallBack(void);
/**********************************************************************************************************************
 *  MAIN FUNCTION
 *********************************************************************************************************************/

int main(void)
{
	/*Step 1 : System Clock is 16 MHz From HSI*/
	MCL_RCC_vInitSysClk(&RCC_G_Config);

	/*Step 2 : init SPI master */
	MCL_SPI_vMasterInit(SPI1, &SPI_Mstr_Config);

	/*Step 3 : init TFT */
	HAL_TFT_vInit() ;


   /*Step 4 : Display Image*/
	HAL_TFT_vDisplayImage(Shafeeq_Arr) ;

	/* Loop forever */
	while(1)
	{

	}
}

void SPI_vReceiveCallBack(void)
{

}
