/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STD_TYPES.h"
#include "MCAL_RCC_Interface.h"
#include "MCAL_RCC_Private.h"
#include "MCAL_RCC_Config.h"

#include "MCAL_GPIO_Interface.h"
#include "MCAL_GPIO_Config.h"

#include "MCAL_EXTI_Interface.h"

#include "MCAL_STK_Interface.h"
/***********************
 * CONSTANT MACROS
 **********************/
#define GPIO_LED_PORT	GPIOA
#define LED1_PIN		GPIO_PIN8
#define LED2_PIN		GPIO_PIN9
#define LED3_PIN		GPIO_PIN10
/**********************************************************************************************************************
 *  Global Variables
 *********************************************************************************************************************/
u8 Global_au8IRFrame[35];
u8 IR_u8Data = 0;
/**********************************************************************************************************************
 *  FUNCTION PROTOTYPE
 *********************************************************************************************************************/

void IR_vReceiveCallBack(void);
void IR_vTakeActionCallBack(void);
/**********************************************************************************************************************
 *  MAIN FUNCTION
 *********************************************************************************************************************/

int main(void)
{
  MCL_RCC_vInitSysClk(&RCC_GPIO_Config);

	MCL_STK_vInit(&STK_G_Config);

	EXTI_G_Cfg[EXTI0].IRQ_pCallBack = IR_vReceiveCallBack;
	MCL_EXTI_vInit(&EXTI_G_Cfg[EXTIRQ0_A0]);
	MCL_STK_vSetIntervalPeriodic(100000 , NULL_PTR);

   	MCL_GPIO_vSetPinCfg(GPIO_LED_PORT, LED1_PIN, &GPIO_LED_Config);
   	MCL_GPIO_vSetPinCfg(GPIO_LED_PORT, LED2_PIN, &GPIO_LED_Config);
   	MCL_GPIO_vSetPinCfg(GPIO_LED_PORT, LED3_PIN, &GPIO_LED_Config);

/* Loop forever */
	while(1)
	{

	}
}

void IR_vReceiveCallBack(void)
{
	static STD_Bool Static_xEdge = FALSE;
	static u8 Static_u8FrameIndex = 0;
	u32 Local_u32Period = 0;
	if(Static_u8FrameIndex < 35)
	{
	if(Static_xEdge == FALSE)
	{
		Static_xEdge = TRUE;
		MCL_STK_vRestartTimer();
	}else
	{
		Local_u32Period = MCL_STK_u32GetElapsed();
		if(Local_u32Period < 15000 && Local_u32Period > 10000)
		{
			Global_au8IRFrame[0] = 1;
			Static_u8FrameIndex++;
		}else if (Local_u32Period < 2400 && Local_u32Period > 2000)
		{
			Global_au8IRFrame[Static_u8FrameIndex++] = 1;
		} else if (Local_u32Period < 1500 && Local_u32Period > 1000)
		{
			Global_au8IRFrame[Static_u8FrameIndex++] = 0;
		}
		Static_xEdge = FALSE;
	}
	}
	else
	{
		Static_u8FrameIndex = 0;
		IR_vTakeActionCallBack();
	}
}
void IR_vTakeActionCallBack(void)
{


	for(u8 Local_u8LoopCounter = 0; Local_u8LoopCounter < 8; Local_u8LoopCounter++)
	{
		ASSIGN_BIT(IR_u8Data,Local_u8LoopCounter ,Global_au8IRFrame[Local_u8LoopCounter+17]);
	}
	switch(IR_u8Data)
	{
	case 12:
		MCL_GPIO_vDirectPinSetter(GPIO_LED_PORT, LED1_PIN, PIN_SET);
		break;
	case 24:
		MCL_GPIO_vDirectPinSetter(GPIO_LED_PORT, LED2_PIN, PIN_SET);
		break;
	case 94:
		MCL_GPIO_vDirectPinSetter(GPIO_LED_PORT, LED3_PIN, PIN_SET);
		break;
	}

}
